swagger: "2.0"
info:
  description: "Elocker 180.166.27.198"
  version: "1.0.0"
  title: "Elocker API"
host: "127.0.0.1:8080"
basePath: "/"
tags:
  - name: "Locker"
    description: "Operation about locker"
  - name: "Authorization"
    description: "Operation about authorization"
  - name: "User"
    description: "Operations about user"
  - name: "Log"
    description: "Operations about logs"
  - name: "Login"
    description: "Operations about login"
  - name: "Update"
    description: "Operations about update"
schemes:
  - "https"
  - "http"
paths:
  /update/check:
    get:
      tags:
        - "Update"
      summary: "check update"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/User-Agent'
        - $ref: '#/parameters/App-Version'
      responses:
        210:
          description: "Need update"
        211:
          description: "Do not need update"
        500:
          description: "Unknow error"
  /locker/get:
    get:
      tags:
        - "Locker"
      summary: "Get single or all locker"
      description: "if param serial is omitted, then all lockers will return"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - name: "serial"
          in: "query"
          description: "serial of the locker"
          type: "string"
      responses:
        200:
          description: "successful operation"
        401:
          description: "unauthorized request"
        500:
          description: "unknow error"
  /locker/add:
    post:
      tags:
        - "Locker"
      summary: "Add a new locker to the database"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "post body data"
          required: true
          schema:
            type: object
            properties:
              serial:
                type: "string"
              description:
                type: "string"

      responses:
        200:
          description: "Operation successful"
        401:
          description: "Unauthorized request"
        500:
          description: "unknown error"
        603:
          description: "invalid serial number"
        604:
          description: "duplicate serial number"
  /locker/update:
    post:
      tags:
        - "Locker"
      summary: "modify locker description"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "post body data"
          required: true
          schema:
            type: object
            properties:
              serial:
                type: "string"
              description:
                type: "string"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        401:
          description: "Unauthorized request"
  /locker/transfer:
    post:
      tags:
        - "Locker"
      summary: "transfer locker"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: ""
          required: true
          schema:
            type: "object"
            properties:
              serial:
                type: "string"
                description: "locker serial"
              toAccount:
                type: "string"
                description: "phone number to authorize to"
      responses:
        200:
          description: "Operation successsful"
        401:
          description: "Unauthorized request"
        500:
          description: "Unknow error"
        605:
          description: "Invalid to account"
  /locker/delete:
    post:
      tags:
        - "Locker"
      summary: "delete lockers"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "locker serial array which to delete"
          required: true
          schema:
            type: "object"
            properties:
              lockerSerials:
                type: "array"
                items:
                  type: "string"
                  description: "locker serials array"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "Unknow error"
        401:
          description: "Unauthorized request"
  /authorization/get:
    get:
      tags:
        - "Authorization"
      summary: "Get authorization of current user"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - name: "toAccount"
          in: "query"
          type: "string"
          description: "the phone number which to authorise to"
        - name: "serial"
          in: "query"
          type: "string"
          description: "related serial of locker"
      responses:
        200:
          description: "successful operation"
        401:
          description: "unauthorized request"
        500:
          description: "unknown error"
  /authorization/add:
    post:
      tags:
        - "Authorization"
      summary: "Add a new authorization"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "Authorization entry"
          required: true
          schema:
            $ref: "#/definitions/Authorization"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknown error"
        401:
          description: "Unauthorized request"
  /authorization/update:
    post:
      tags:
        - "Authorization"
      summary: "modify a authorization"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "Authorization entry"
          required: true
          schema:
            $ref: "#/definitions/AuthorizationUpdate"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        401:
          description: "Unauthorized request"
  /authorization/delete:
    post:
      tags:
        - "Authorization"
      summary: "delete authorization by ids"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "Authorization ids that to delete"
          required: true
          schema:
            type: "object"
            properties:
              appid:
                type: "string"
              sign:
                type: "string"
              ids:
                description: "id and serial object array"
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                      format: "int64"
                      description: "Authorization Id"
                    serial:
                      type: "string"
                      description: "Serial number of locker"
            example:
              ids:
                - id:1000 ,serial: "abdcef"
                - id:10001 , serial: "defghi"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        401:
          description: "Unauthorized request"
  /log/get:
    get:
      tags:
        - "Log"
      summary: "Get single or all operation log"
      description: "if param serial is omitted, then all log will return"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - name: "serial"
          in: "query"
          description: "serial of the locker"
          type: "string"
        - name: "startTime"
          in: "query"
          description: "start time of the log"
          type: "string"
        - name: "endTime"
          in: "query"
          description: "end time of the log"
          type: "string"
        - name: "page"
          in: "query"
          description: "page index, begins at 0"
          type: "integer"
          format: "int32"
        - name: "pageSize"
          in: "query"
          description: "page size"
          type: "integer"
          format: "int32"
      responses:
        200:
          description: "successful operation"
        500:
          description: "unknow error"
        401:
          description: "unauthorized request"
  /log/add:
    post:
      tags:
        - "Log"
      summary: "Add a operation log"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "operation log to add"
          required: true
          schema:
            $ref: "#/definitions/OperationLog"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        401:
          description: "Unauthorized request"
  /user/get:
    get:
      tags:
        - "User"
      summary: "get infomation about current login user"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        401:
          description: "Unauthorized request"
  /user/add:
    post:
      tags:
        - "User"
      summary: "add a new user"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "postData"
          description: "Add a new user"
          required: true
          schema:
            type: "object"
            properties:
              phoneNum:
                type: "string"
              userName:
                type: "string"
              password:
                type: "string"
                description: "Encrypt password "
              email:
                type: "string"
              code:
                type: "string"
                description: "verification code"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        606:
          description: "Invalid phone number"
        609:
          description: "Incorrect verificaiton number"
  /user/getCode:
    post:
      tags:
        - "User"
      summary: "get verification code for user register"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "postData"
          required: true
          schema:
            type: "object"
            properties:
              phoneNum:
                type: "string"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "Unknow error"
        606:
          description: "Phone number can not be empty"
        610:
          description: "Send message failed"
        611:
          description: "Short message gateway is unreachable"
  /user/resetPassword:
    post:
      tags:
        - "User"
      summary: "Reset password"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "postData"
          description: "Reset password"
          required: true
          schema:
            type: "object"
            properties:
              phoneNum:
                type: "string"
              password:
                type: "string"
              code:
                type: "string"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "Unknow error"
        606:
          description: "Phone number can not be empty"
        609:
          description: "Verification code is incorrect"
        613:
          description: "User has not registered before"
  /user/changePassword:
    post:
      tags:
        - "User"
      summary: "Change password"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "change password for user"
          required: true
          schema:
            type: "object"
            properties:
              oldpass:
                type: "string"
                description: "encryption password text"
              newpass:
                type: "string"
                description: "encryption password text"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        601:
          description: "Incorrect username or password"
  /user/changePhoneNum:
    post:
      tags:
        - "User"
      summary: "Change Phone Number"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/App-Id'
        - $ref: '#/parameters/Token'
        - $ref: '#/parameters/Api-Key'
        - in: "body"
          name: "postData"
          description: "change phone number for user"
          required: true
          schema:
            type: "object"
            properties:
              newPhoneNum:
                type: "string"
                description: "new phone number"
              code:
                type: "string"
                description: "verification code"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        609:
          description: "Incorrect verification code"
  /login/login:
    post:
      tags:
        - "Login"
      summary: "Login in"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/User-Agent'
        - $ref: '#/parameters/App-Version'
        - in: "body"
          name: "postData"
          description: "login"
          required: true
          schema:
            type: "object"
            properties:
              phoneNum:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Operation successsful"
        500:
          description: "unknow error"
        601:
          description: "Incorrect username or password"
        602:
          description: "Retry too many times"
parameters:
  App-Id:
    in: header
    name: App-Id
    required: true
    type: string
    description: "App-Id"
  Token:
    in: header
    name: Token
    required: true
    type: string
    description: "Token"
  Api-Key:
    in: header
    name: Api-Key
    required: true
    type: string
    description: "Api key"
  User-Agent:
    in: header
    name: User-Agent
    required: true
    type: string
    description: "the string to describe the client os and version information"
  App-Version:
    in: header
    name: App-Version
    required: true
    type: string
    description: "The version of client app"
definitions:
  Authorization:
    type: "object"
    properties:
      serial:
        type: "string"
        description: "serial of the locker to authorize"
      toAccount:
        type: "string"
        description: "phone number of acount to authorise to"
      startTime:
        type: "string"
        description: "authorization start time string"
      endTime:
        type: "string"
        description: "authorization end time string"
      description:
        type: "string"
        description: "authorization name"
      weekday:
        type: "string"
      dailyStartTime:
        type: "string"
      dailyEndTime:
        type: "string"
    example:
      serial: "abcdef"
      toAccount: "13167017116"
      startTime: "2019-06-05 00:00:00"
      endTime: "2019-06-06 00:00:00"
      description: "First Authorization"
      weekday: "1,2,3,4,5,6,7"
      dailyStartTime: "00:00:00"
      dailyEndTime: "23:59:00"
  AuthorizationUpdate:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      startTime:
        type: "string"
      endTime:
        type: "string"
      description:
        type: "string"
    example:
      appid: "15851841387"
      sign: "6079dd110df75e04c490b362d3a58b8c"
      id: 101010
      startTime: "2019-06-05 00:00:00"
      endTime: "2019-06-06 00:00:00"
      description: "Modified Authorization"
  OperationLog:
    type: "object"
    properties:
      serial:
        type: "string"
        description: "locker serial"
      operation:
        type: "string"
        enum: ["Open","Lock","Add_Locker","Delete_Locker",
               "Modify_Authorization","Add_Authorization","Delete_Authorization","Login","Login_Out"]
        description: "operation name"
      sTime:
        type: "string"
        description: "the time when add the log"
      description:
        type: "string"